### ISSUE TITLE
failed to allocate 0 bytes

### ISSUE THREAD

**Issue by nemccarthy** [luxonis/esp32-spi-message-demo#11]
Running against the latest main branch `ea52682`. With the BW1092 esp32 I keep seeing the following from `idf.py monitor` when running the people-tracker demo using the latest main from experiments gen2-people-tracker on the myriad;

```
req_data | spi_get_size response: 0, ret: 1
sending spi_get_size cmd.
receive spi_get_size response from remote device...
response: 0
failed to allocate 0 bytes
sending POP_MESSAGES cmd.
receive POP_MESSAGES response from remote device...
```

The demos were previously working on an older version of the repo.

**Comment by Luxonis-Brandon** [comment]
Will need @Erol444 or @themarpe to help on this one.

**Comment by themarpe** [comment]
@nemccarthy thanks for reporting - will be taking a closer look by the end of the week

**Comment by liuli2008212** [comment]
Has the problem been resolved?
I have this problem too.

My environment as below:
ubuntu 20.04LTS
opencv-python==4.5.1.48
blobconverter==1.0.0

when flash bootloader with depthai==2.8.0.0.dev+b0410e916bc92656765313ea809670e4cab7e4ae
and flash DAP with depthai==2.2.1.0
people-tracker run in ESP32,uart printf as below,about 3 frames per second,too slow:
![2021-09-09 10-54-13 的屏幕截图](https://user-images.githubusercontent.com/26320579/133200026-ca468a54-367d-4d48-a707-6b5c196903b4.png)


when flash bootloader with depthai==2.8.0.0.dev+b0410e916bc92656765313ea809670e4cab7e4ae
and flash DAP with depthai==2.10.0.0
people-tracker run in ESP32,uart printf as below,no result:
![2021-09-14 13-02-49 的屏幕截图](https://user-images.githubusercontent.com/26320579/133200049-9260edce-d2fe-4927-985f-0abb04b009a8.png)

**Comment by Erol444** [comment]
Hello @liuli2008212 , could you also try flashing bootloader/pipeline from the latest develop of depthai-python? There were quite a few changes, so it might have been fixed already.

**Comment by liuli2008212** [comment]
Hello @Erol444 is the lastest depthai-python==2.10.0.0? I flashed bootloader by V2.10.0.0,but the BW1092 is not working,esp32 printf : 
Timeout: no response from remote device
failed to recv packet

**Comment by themarpe** [comment]
@liuli2008212 for latest you could try `develop` branch of this repository as well as `develop` branch of `depthai-python` repository (use `examples/install_requirements.txt` to install the develop version - there is also an updated bootloader there)

Note that there are some issues still even on that branch, which we are working on to fix. Most likely in 2-3 weeks

**Comment by liuli2008212** [comment]
@themarpe thank you for your support, I used the bootloader,but it's not results,as below(DAP with  depthai==2.10.0.0.dev0+8f000265e6da26348686d58024e49297374a6147):
![2021-09-17 10-59-42 的屏幕截图](https://user-images.githubusercontent.com/26320579/133720061-6b5b979e-546f-4a99-a778-9ad430d6c875.png)

if DAP with depthai==2.2.1.0,as below(too low ,only is 3fps):
![2021-09-17 11-15-58 的屏幕截图](https://user-images.githubusercontent.com/26320579/133720278-e700b452-cbf2-4b0e-90e3-6f6cc0ade73b.png)

**Comment by themarpe** [comment]
@liuli2008212 thanks for testing it out. 
We have stability issues with SPI in latest `develop` and are working on fixing that along with speed and other improvements.
ETA is around 1-3 weeks depending on some other tasks at hand.
Will let you know once its fixed:)

**Comment by liuli2008212** [comment]
Hi, @themarpe  Has it been resolved?

**Comment by themarpe** [comment]
Hi @liuli2008212 
This was mostly addressed (although we hadn't refactored the SPI as a whole yet)
Can you check out the latest `develop` on both the DepthAI side and `esp32-spi-message-demo` side (make sure to update submodules as well). 
This should get you up and running.

I'll be making a release so this will be part of main branches soon as well

**Comment by themarpe** [comment]
@liuli2008212 I've updated main branch of the repo with added changes and with DepthAI 2.11.0 compatibility
